alter table public.cms_content
  drop constraint if exists cms_content_key_check;

alter table public.cms_content
  add constraint cms_content_key_check
  check (key in ('navLinks', 'stats', 'missionCards', 'events', 'members', 'partners', 'announcements', 'testimonials', 'faqs'));

create table if not exists public.get_involved_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  role_area text not null,
  skills text not null,
  experience_level text,
  twitter_url text,
  github_url text,
  portfolio_url text,
  looking_for text not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.get_involved_submissions enable row level security;

drop policy if exists "No public read submissions" on public.get_involved_submissions;
create policy "No public read submissions"
on public.get_involved_submissions
for select
to anon, authenticated
using (false);

drop policy if exists "No public write submissions" on public.get_involved_submissions;
create policy "No public write submissions"
on public.get_involved_submissions
for insert
to anon, authenticated
with check (false);
